"""Create jobs table

Revision ID: e55052041658
Revises:
Create Date: 2025-06-29 20:30:37.275443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e55052041658"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.String(length=255), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("role_title", sa.String(length=255), nullable=False),
        sa.Column("job_website", sa.String(length=100), nullable=False),
        sa.Column("job_url", sa.Text(), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("salary_range", sa.String(length=100), nullable=True),
        sa.Column("job_description", sa.Text(), nullable=True),
        sa.Column("requirements", sa.Text(), nullable=True),
        sa.Column("when_scraped", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("is_new", sa.Boolean(), nullable=True),
        sa.Column("is_relevant", sa.Boolean(), nullable=True),
        sa.Column("is_processed", sa.Boolean(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_id", "job_website", name="unique_job_per_site"),
    )
    op.create_index("idx_is_new", "jobs", ["is_new"], unique=False)
    op.create_index("idx_is_processed", "jobs", ["is_processed"], unique=False)
    op.create_index("idx_is_relevant", "jobs", ["is_relevant"], unique=False)
    op.create_index("idx_job_website", "jobs", ["job_website"], unique=False)
    op.create_index("idx_last_seen", "jobs", ["last_seen"], unique=False)
    op.create_index("idx_when_scraped", "jobs", ["when_scraped"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_when_scraped", table_name="jobs")
    op.drop_index("idx_last_seen", table_name="jobs")
    op.drop_index("idx_job_website", table_name="jobs")
    op.drop_index("idx_is_relevant", table_name="jobs")
    op.drop_index("idx_is_processed", table_name="jobs")
    op.drop_index("idx_is_new", table_name="jobs")
    op.drop_table("jobs")
    # ### end Alembic commands ###
